apiVersion: v2
name: my-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"

dependencies:
  - name: redisq
    version: 6.0.8
    repository: https://charts.bitnami.com/bitnamic23
  - name: postgresql
    version: 10.3.17
    repository: https://charts.bitnami.com/bitnamic34
  - name: nginx
    version: 1.19.10
    repository: https://charts.bitnami.com/bitnamic67
  - name: my-custom-component
    version: 2.3.1
    repository: https://my-custom-repo.com/charts

